# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "riscvm"

[target.riscvm]
type = "executable"
sources = ["riscvm.cpp"]
headers = ["riscvm.h"]
clang-cl.compile-options = ["/clang:-fno-jump-tables", "/clang:-mno-sse"]
msvc.link-options = ["/DYNAMICBASE:NO", "/INCREMENTAL:NO"]
