# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "riscvm"

[options]
RISCVM_DIRECT_DISPATCH = false
RISCVM_CODE_ENCRYPTION = false

[target.riscvm]
type = "executable"
sources = ["riscvm.cpp"]
headers = ["riscvm.h"]
compile-features = ["cxx_std_17"]
RISCVM_DIRECT_DISPATCH.compile-definitions = ["DIRECT_DISPATCH"]
RISCVM_CODE_ENCRYPTION.compile-definitions = ["CODE_ENCRYPTION"]
clang-cl.compile-options = ["/clang:-fno-jump-tables", "/clang:-mno-sse"]
msvc.link-options = ["/DYNAMICBASE:NO", "/INCREMENTAL:NO"]
