# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[cmake]
version = "3.19"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "payload"
languages = ["CXX"]
cmake-before = "set(CMAKE_CONFIGURATION_TYPES Debug Release)"
include-after = ["cmake/riscvm.cmake"]
msvc-runtime = "static"

[fetch-content.phnt]
url = "https://github.com/mrexodia/phnt-single-header/releases/download/v1.2-4d1b102f/phnt.zip"

[template.riscvm]
type = "executable"
add-function = "add_riscvm_executable"

# Windows implementation of the riscvm syscalls (for debugging only)
[target.riscvm-crt0]
type = "shared"
sources = ["crt/riscvm-crt0.cpp"]

[target.payload]
type = "riscvm"
sources = [
	"src/main.cpp",
	"crt/minicrt.c",
	"crt/minicrt.cpp",
]
include-directories = [
	"include",
]
link-libraries = [
    "riscvm-crt0",
	"phnt::phnt",
]
compile-features = ["cxx_std_17"]
msvc.link-options = [
	"/INCREMENTAL:NO",
	"/DEBUG",
]
